# Generated by Django 2.1.4 on 2018-12-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0016_auto_20181228_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('flag_ID', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('details', models.CharField(help_text='Details about the mistake', max_length=100)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='credited_flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='uncredited_flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='flagged_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(help_text='Chapter name (according to syllabus)', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, help_text='Enter your email', max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='flag',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagger', to='question_model.Customer'),
        ),
    ]
